version: '3'
services:
    mysql:
      image: mysql:5.7.18
      ports:
        - "3306:3306"
      environment:
        - MYSQL_USER=root
        - MYSQL_PASSWORD=root
        - MYSQL_DATABASE=menu
      networks:
        - network
networks:
  network:
    driver: bridge